- R/create.boxplot.R
- man/create.boxplot.Rd
This is an work around to be able to set different text labels on each panel
Data: https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/files/7003378/create.boxplot.data.txt
```R
data <- read.table(file = 'create.boxplot.data.txt', header = TRUE);
dummy.data <- data.frame(
expression_score = NA,
sex = 'Male',
gene = 'DDX3X'
);
data <- rbind(data, dummy.data);
data <- data[order(data$gene, data$sex),]
sex.colours <- replace(data$sex, which(data$sex == 'Male'),'dodgerblue');
sex.colours <- replace(sex.colours, which(data$sex == 'Female'), 'pink');
ymin <- min(data$expression_score, na.rm = TRUE)
ymax <- max(data$expression_score, na.rm = TRUE)
ymax <- ymax + (ymax - ymin) * 0.15
p <- create.boxplot(
formula = expression_score ~ sex | gene,
data = data,
add.stripplot = TRUE, …
```
> Enable create.boxplot to print different text label on each panel

- DESCRIPTION
- NEWS
- R/create.boxplot.R
- R/parse.formula.R
- man/create.boxplot.Rd
Fixes problem with boxplot `points.col` in Issue #4 with lattice group/subscript arguments.
> Fix boxplot colour group bug

- R/legend.grob.R
Closes #8 
The values mentioned in the issue are explained in this comment (found earlier in the file).
```
```
Instead of creating multiple comments to explain the same value, it made more sense to change the repeated hardcoded values to variables.
```
legends <- list(
legend = list(
colours = c('orange', 'chartreuse4', 'darkorchid4'),
labels = c('Group 1', 'Group 2', 'Group 3'),
title = expression(underline('Legend #1'))
),
point = list(
colours = c('firebrick3', 'lightgrey'),
labels = c('A label', 'A longer label'),
cex = 1.5
)
)
legend.grob(
legends = legends,
border = list(col = 'blue', lwd = 2, lty = 3),
border.padding = 1.5,
between.row = 3
);
```
> Refactor hardcoded "magic numbers" in legend.grob

- .github/CODEOWNERS
Added a test `CODEOWNERS` file with myself and the software working group. This is not a permanent setup. For example, Paul should probably be included on the open source packages for which he's listed as the maintainer on CRAN.
> Test CODEOWNERS

- DESCRIPTION
- NAMESPACE
- NEWS
- R/create.qqplot.fit.confidence.interval.R
- R/critical.value.ks.test.R
- man/critical.value.ks.test.Rd
S3 generic functions allow a function to execute differently depending on the type of object that is passed to the function. This is a feature in R that allows some OOP-ish patterns. Once an S3 generic function is defined, it can be extended by adding a class name to the end of the function name (separated by a period `.`).
There is a function in the base R `stats` package called `ks.test()`. In BPG, there is a function called `ks.test.critical.value()` (originally part of BL.statistics.general). In the most recent version of R, `ks.test` was converted to an S3 generic, causing our function to appear as an extension of this function. However, the two are unrelated in their implementation. This caused the CRAN checks to raise the following error:
```
Check: S3 generic/method consistency …
```
> Resolve S3 Generic Naming Conflict

- DESCRIPTION
- NEWS
- R/create.polygonplot.R
See #13 for issue/solution description. There are slight differences between the parameter types, so I did not end up using the utility function idea - keeping the existing if/else structure instead.
```
fill.matrix <- function(x, gene, data){
for(i in x){
gene[i, 1:i] <- rep(NA, i);
gene[i, i:58] <- rep(as.numeric(data[i]), 58-i+1);
}
return(gene);
}; 
get.polygon.data <- function(num){
data1 <- microarray[num, 1:58];
gene1 <- as.data.frame(matrix(nrow = 58, ncol = 58));
gene1 <- fill.matrix(1:58, gene1, data1);
gene1 <- t(matrix(unlist(gene1), ncol = 58, byrow = TRUE));
polygon.data.gene1 <- data.frame(
x = 1:58,
max = apply(gene1, 2, function(x) {max(x, na.rm = TRUE)}),
median = apply(gene1, 2, function(x) {median(x, na.rm = TRUE)}),
min = apply(gene1, 2, function(x) {min(x, na.rm = …
```
> Fix bug in polygonplot

- DESCRIPTION
- NEWS
- metadata.yaml
- src/distance.c
CRAN's checks found these issues in `distance.c`:
```Function Cdist
[UP] unprotected variable names while calling allocating function Rf_install BoutrosLab.plotting.general/src/distance.c:327
[UP] unprotected variable names while calling allocating function Rf_setAttrib(V,?,?) BoutrosLab.plotting.general/src/distance.c:327
[UP] unprotected variable names while calling allocating function Rf_translateChar BoutrosLab.plotting.general/src/distance.c:327
```
These are related to protecting/unprotecting pointers that will be used by R. Calling `PROTECT()` on `attrs` and `names`, then subsequently unprotecting them with `UNPROTECT(3)` (the last 3 protected variables) led to a clean Rchk run.
> Fix C object protection issue

- R/create.polygonplot.R
- man/create.polygonplot.Rd
Closes #24 
See previous BPG behavior from issue. Some of the modifications that I think makes sense since I tried to fix the bug while keeping the general idea of the behavior similar. I think it makes sense to remove the `add.xy.border`/`add.border` parameter entirely and only set the border via `border.col`.
Based on these searches on our github there shouldn't be any disruptions in how border is used:
https://github.com/search?q=org%3Auclahs-cds+add%5C.xy%5C.border+-repo%3Auclahs-cds%2FBoutrosLab+language%3AR+language%3AR&type=Code
https://github.com/search?p=2&q=org%3Auclahs-cds+create.polygonplot+border.col+-repo%3Auclahs-cds%2FBoutrosLab+language%3AR+language%3AR+-repo%3Auclahs-cds%2Fpublic-R-BoutrosLab-plotting-general&type=Code
Results from this PR
```r …
```
> Correctly specify border.col and add.border behavior

- DESCRIPTION
- NEWS
- R/create.boxplot.R
- man/create.boxplot.Rd
@lydiayliu This should fix the boxplot alpha parameter.
[`grDevices::adjustcolor`](https://www.rdocumentation.org/packages/grDevices/versions/3.6.2/topics/adjustcolor) is already imported by lattice.
Fixes #34
> Add alpha parameter to create.boxplot

- DESCRIPTION
- NEWS
- R/create.histogram.R
Fix `create.histogram` to use `ylab.axis.padding` parameter.
```r
set.seed(10)
x <- rnorm(100)
create.histogram(
x,
ylab.label = 'ylab',
ylab.axis.padding = 15
)
```
> Fix ylab.axis.padding parameter in create.histogram

- .github/workflows/pkgdown.yaml
- _pkgdown.yml
Switch jpeg to png to fix black background on images.
Updates a few of the github actions versions as well.
Tested on repo here: https://github.com/stefaneng/github-actions-pkgdown-test
> Update pkgdown github action

- NEWS
- R/create.multipanelplot.R
Replace check that forces use of string with more general check that allows for expressions in x/ylab.labels.
Allows expressions in `xlab.label` and `ylab.label` in `create.multipanelplot`
``` r
library(BoutrosLab.plotting.general)
p1 <- create.histogram(rnorm(100))
create.multipanelplot(
plot.objects = list(p1),
ylab.label = expression(bold('TEST' ~ x^2)),
xlab.label = expression(bold('TEST' ~ y^2))
)
#> Error in ylab.label != "": comparison is not allowed for expressions
```
<sup>Created on 2023-02-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
``` r
library(BoutrosLab.plotting.general)
p1 <- create.histogram(rnorm(100))
create.multipanelplot(
plot.objects = list(p1),
ylab.label = expression(bold('TEST' ~ x^2)),
xlab.label = expression(bold('TEST' ~ y^2))
)
```
<sup>Created …
> Add ability to use expressions in multipanelplot x and y labels

- README.md
Update citation information to match `citation('Boutros.plotting.general')` to keep consistent with changes suggested to VennDiagram README
> Update citation information to match `citation('Boutros.plotting.general')`

- .github/pull_request_template.md
- NEWS
> Add PR template for BPG

- NEWS
- R/create.multipanelplot.R
Multipanelplots were not able to use expressions for `main`. This was fixed for `xlab` and `ylab` in #90 but still was an issue for main title.
-   [x] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files. To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see …
> Add ability to use expressions in main title and ylab.label.right for multipanelplot

- DESCRIPTION
- NEWS
- R/legend.grob.R
In new versions of R (> R v4.3.0), lattice does not allow `labels` to be specified in a `draw.colorkey` without corresponding values for `at`. This change fixes BPG's call to `draw.colorkey` within  `legend.grob`, placing labels equidistant along the range of continuous values.
-   [X] This PR does NOT contain [PHI](https://ohrpp.research.ucla.edu/hipaa/) or germline genetic data. A repo may need to be deleted if such data is uploaded. Disclosing PHI is a [major problem](https://healthitsecurity.com/news/ucla-health-reaches-7.5m-settlement-over-2015-breach-of-4.5m).
-   [X] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files. To automatically exclude such …
> Fix bug with continuous legends

- DESCRIPTION
- NEWS
- R/create.multipanelplot.R
-   [x] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files. To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/.gitignore) for example.
-   [x] I have read the [code review …
> Fix error with expressions in main for multipanelplots

- NEWS
- R/create.boxplot.R
- man/create.boxplot.Rd
Make behavior of axis.lab = NULL for `create.boxplot` consistent with other functions.
``` r
library(BoutrosLab.plotting.general, quietly = T, warn.conflicts = F);
set.seed(10);
simple.data <- data.frame(
x = rnorm(100),
y = sample(1:5, replace = T, size = 100)
);
create.boxplot(
formula = y ~ x,
data = simple.data,
yaxis.lab = NULL
);
```
``` r
create.boxplot(
formula = y ~ x,
data = simple.data,
xaxis.lab = NULL
);
```
<sup>Created on 2023-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Remove axis label with NULL in `create.boxplot`

- DESCRIPTION
- NEWS
- README.md
Updates CRAN link format in `README.md`, which was creating a `NOTE` in CRAN checks.
-   [X] This PR does NOT contain [PHI](https://ohrpp.research.ucla.edu/hipaa/) or germline genetic data. A repo may need to be deleted if such data is uploaded. Disclosing PHI is a [major problem](https://healthitsecurity.com/news/ucla-health-reaches-7.5m-settlement-over-2015-breach-of-4.5m).
-   [X] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files. To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/.gitignore) for …
> Update CRAN links

- DESCRIPTION
- NEWS
- R/export.to.file.R
Similar to #16, these changes rename `print.to.file` to `export.to.file`. This is an issue with our mixed-dotted case naming convention, where function names can be misinterpreted as an S3 method for a nonexistant class (in this case, the `print` method for the class `to.file`). This results in the following error in CRAN's checks.
> ```
> Mismatches for apparent methods not registered:
>print: function(x, ...)
>print.to.file: function(dirname, funcname, data, filename)
> ```
Note, I only considered this a patch (not a breaking change) because this is a private function not exported by the package.
-   [ ] This PR does NOT contain [PHI](https://ohrpp.research.ucla.edu/hipaa/) or germline genetic data. A repo may need to be deleted if such data is uploaded. Disclosing PHI is a [major …
> print.to.file naming conflict

- .github/workflows/r-lib-check.yaml
- DESCRIPTION
- NEWS
-   [x] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files. To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/.gitignore) for example.
-   [x] I have read the [code review …
> Run R CMD check weekly

- .github/workflows/r-lib-check.yaml
- DESCRIPTION
- NEWS
Update to allow `R CMD check` to be triggered manually with workflow dispatch.
-   [x] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files. To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/.gitignore) for …
> Trigger R CMD check with dispatch

- .Rbuildignore
- .cicd-env
- .github/workflows/CICD-base.yaml
This is a super-simple change that moves the linting configuration from the GitHub workflow file to a new `.cicd-env` file. There are no "real" changes to this package.
This change enables the new bllint script from https://github.com/uclahs-cds/docker-CICD-base/pull/60 to lint a checked-out copy of this repository for easier development.
-   [x] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, …
> Move linting configuration to .cicd-env file

- .github/pull_request_template.md
This PR replaces links to the old Confluence wiki in all plain-text files in this repository. I manually created a table of replacement links and used a regex to find and replace them - it's very possible something was mangled in that process, so whoever reviews this should confirm each of the replacement links.
| Old Link | Replacement Link |
| -------- | ---------------- |
| <https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Guidelines> | <https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines> |
| <https://confluence.mednet.ucla.edu/pages/viewpage.action?spaceKey=BOUTROSLAB&title=GitHub+Standards#GitHubStandards-Branchprotectionrule> | <https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStand …
> Autofix broken Confluence links

- man/create.barplot.Rd
A very common plot we make in the lab is a heatmap with a barplot on the right, using `plot.horizontal = TRUE`. 
For the heatmap, I typically use `same.as.matrix = TRUE` when not clustering, thus I know the order of row/columns of the input data will exactly match the order in the plot.  Then I make sure the barplot data rows are in the same order as the heatmap data rows, and use `disable.factor.sorting = TRUE.`
However, the order of rows in the heatmap and barplot get *misaligned* in this approach, that's because `create.barplot` fills in the bars from the bottom to the top of the plot, although I assumed the opposite (*i.e.* I thought the order of rows in the barplot would match the order of rows in the input data).
Thus I updated the documentation to try and clarify this.
-   [x] This …
> update barplot documentation for plot.horizontal

- DESCRIPTION
- NEWS
- R/create.barplot.R
- R/create.boxplot.R
- R/prep.inputs.R
- tests/testthat/test-prep.inputs.R
Sets up reusable functionality to validate the `sample.order` argument in some plotting functions. Additionally, this refactor allows the functionality to be unit-tested.
-   [X] This PR does NOT contain [PHI](https://ohrpp.research.ucla.edu/hipaa/) or germline genetic data. A repo may need to be deleted if such data is uploaded. Disclosing PHI is a [major problem](https://healthitsecurity.com/news/ucla-health-reaches-7.5m-settlement-over-2015-breach-of-4.5m).
-   [X] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files. To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) …
> Prep sample order input

- NEWS.md
- man/create.scatterplot.Rd
- man/legend.grob.Rd
Fixes two NOTEs in R CMD check.
```
Rd file 'create.scatterplot.Rd':
\examples lines wider than 100 characters:
These lines will be truncated in the PDF manual.
```
```
* checking Rd cross-references ... NOTE
Found the following Rd file(s) with Rd \link{} targets missing package
anchors:
legend.grob.Rd: draw.key
Please provide package anchors for all Rd \link{} targets not in the
```
-   [X] This PR does NOT contain [PHI](https://ohrpp.research.ucla.edu/hipaa/) or germline genetic data. A repo may need to be deleted if such data is uploaded. Disclosing PHI is a [major problem](https://healthitsecurity.com/news/ucla-health-reaches-7.5m-settlement-over-2015-breach-of-4.5m).
-   [X] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, …
> Manual fixes for CRAN

- DESCRIPTION
- NEWS
- src/ks.c
This PR addresses time-sensitive CRAN requirements (detailed in #192). `R CMD check` passes locally and on CRAN (including Winbuilder). 
```
* using log directory 'd:/RCompile/CRANguest/R-devel/BoutrosLab.plotting.general.Rcheck'
* using R Under development (unstable) (2024-09-30 r87204 ucrt)
* using platform: x86_64-w64-mingw32
* R was compiled by
gcc.exe (GCC) 13.2.0
GNU Fortran (GCC) 13.2.0
* running under: Windows Server 2022 x64 (build 20348)
* using session charset: UTF-8
* checking for file 'BoutrosLab.plotting.general/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'BoutrosLab.plotting.general' version '7.1.2'
* checking CRAN incoming feasibility ... [11s] OK
* checking package namespace information ... OK
* checking package dependencies ... OK
* …
```
> CRAN Rcpp dependency fixes

- DESCRIPTION
- NEWS
- R/force.colour.scheme.R
Adds a new color for Gleason Sum of 10 and removes extra grey that is mistakenly in the colour scheme
-   [x] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files. To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/ …
> Add new Gleason sum color

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
Addresses the following false-positive `R CMD check` note:
> `Skipping checking math rendering: package 'V8' unavailable`
-   [x] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files. To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see …
> Optional V8 dev dependency for HTML vignette
